version: '3'

services:

  app:
    container_name: app
    image: dataindataout/opsjump
    hostname: app
    environment:
      - VAULT_ADDR=http://vault:9200
    volumes:
      - ./scripts/initiate_vault.sh:/initiate_vault.sh
      - ./scripts/initiate_replication.sh:/initiate_replication.sh
      - ./scripts/initiate_proxysql.sh:/initiate_proxysql.sh
      - ./scripts/create_user.sh:/create_user.sh
    command: tail -f /dev/null

  vault:
    container_name: vault
    hostname: vault
    image: dataindataout/docker-vault
    ports:
      - "9200:8200"
    volumes:
      - ./vault.hcl:/etc/vault.hcl
    environment:
      - VAULT_ADDR=http://vault:9200
    command: "server -config=/etc/vault.hcl"

  mysqlprimary:
    container_name: mysqlprimary
    image: dataindataout/mysql
    hostname: mysqlprimary
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    command: >
        --server-id=1
        --log-bin
    
  mysqlreplica:
    container_name: mysqlreplica
    image: dataindataout/mysql
    hostname: mysqlreplica
    ports: 
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    command: >
      --server-id=2
      --read-only=ON
      --log-bin
    depends_on: 
         - 'mysqlprimary'

  proxysql:
    container_name: proxysql
    image: dataindataout/docker-proxysql
    hostname: proxysql
    links:
      - mysqlprimary
      - mysqlreplica
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf
    environment:
      - CLUSTER_NAME=test
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PROXY_USER=root
      - MYSQL_PROXY_PASSWORD=password
      - DISCOVERY_SERVICE=false
    expose:
      - "6032"
    ports:
      # ProxySQL admin port for MySQL commands
      - "6032:6032"
      # ProxySQL main port
      - "6033:6033"

  openldap:
    container_name: openldap
    image: dataindataout/docker-openldap
    hostname: ldap
    ports:
      - "389:389"
      - "639:639"
    environment:
      - LDAP_ORGANISATION=proxysql
      - LDAP_DOMAIN=proxysql.com
      - LDAP_ADMIN_PASSWORD=password
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/

  phpldapadmin:
    image: dataindataout/docker-phpldapadmin
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS=false:
    ports:
      - "8080:80"
    depends_on:
      - openldap

