version: '3'

################################################
# adjacents master docker-compose file
# updated January 2018
# author: Valerie Parham-Thompson

services:

################################################
# operations server; run commands here
  app:
    container_name: app
    image: dataindataout/opsjump
    hostname: app
    # environment:
    #   - VAULT_ADDR=http://vault:9200
    volumes:
      - ./scripts/initiate_replication.sh:/initiate_replication.sh
      # - ./scripts/initiate_vault.sh:/initiate_vault.sh
      # - ./scripts/initiate_proxysql.sh:/initiate_proxysql.sh
      # - ./scripts/install_ldap.sh:/install_ldap.sh
      # - ./scripts/create_user.sh:/create_user.sh
    command: tail -f /dev/null

################################################
# oracle mysql community 5.7
  # mysqlprimary:
  #   container_name: mysqlprimary
  #   image: dataindataout/mysql
  #   hostname: mysqlprimary
  #   ports: 
  #     - "3301:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_ROOT_HOST: '%'
  #   command: >
  #       --server-id=1
  #       --log-bin
    
  # mysqlreplica:
  #   container_name: mysqlreplica
  #   image: dataindataout/mysql
  #   hostname: mysqlreplica
  #   ports: 
  #     - "3302:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_ROOT_HOST: '%'
  #   command: >
  #     --server-id=2
  #     --read-only=ON
  #     --log-bin
  #   depends_on: 
  #        - 'mysqlprimary'

################################################
# mariadb + myrocks 
  mariarocksprimary:
    container_name: mariarocksprimary
    image: dataindataout/mariarocks
    hostname: mariarocksprimary
    ports: 
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    command: >
        --server-id=3
        --log-bin

  mariarocksreplica:
    container_name: mariarocksreplica
    image: dataindataout/mariarocks
    hostname: mariarocksreplica
    ports: 
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    command: >
        --server-id=4
        --log-bin

################################################
# mariadb + tokudb
  # mariatokuprimary:
  #   container_name: mariatokuprimary
  #   image: dataindataout/mariatoku
  #   hostname: mariatokuprimary
  #   ports: 
  #     - "3305:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_ROOT_HOST: '%'
  #   command: >
  #       --server-id=5
  #       --log-bin

  # mariatokureplica:
  #   container_name: mariatokureplica
  #   image: dataindataout/mariatoku
  #   hostname: mariatokureplica
  #   ports: 
  #     - "3307:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_ROOT_HOST: '%'
  #   command: >
  #       --server-id=7
  #       --log-bin

################################################
# mariadb 10.3
  # mariaprimary:
  #   container_name: mariaprimary
  #   image: dataindataout/mariadb:10.3
  #   hostname: mysqlprimary
  #   ports: 
  #     - "3308:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_ROOT_HOST: '%'
  #   command: >
  #       --server-id=8
  #       --log-bin
    
  # mariareplica:
  #   container_name: mariareplica
  #   image: dataindataout/mariadb:10.3
  #   hostname: mysqlreplica
  #   ports: 
  #     - "3309:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 'password'
  #     MYSQL_ROOT_HOST: '%'
  #   command: >
  #     --server-id=9
  #     --read-only=ON
  #     --log-bin
  #   depends_on: 
  #         - 'mariaprimary'

################################################
# hashicorp vault
  # vault:
  #   container_name: vault
  #   hostname: vault
  #   image: dataindataout/docker-vault
  #   ports:
  #     - "9200:8200"
  #   volumes:
  #     - ./vault.hcl:/etc/vault.hcl
  #   environment:
  #     - VAULT_ADDR=http://vault:9200
  #   command: "server -config=/etc/vault.hcl"

################################################
# proxysql
  # proxysql:
  #   container_name: proxysql
  #   image: dataindataout/docker-proxysql
  #   hostname: proxysql
  #   links:
  #     - mysqlprimary
  #     - mysqlreplica
  #   volumes:
  #     - ./proxysql.cnf:/etc/proxysql.cnf
  #   environment:
  #     - CLUSTER_NAME=test
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_PROXY_USER=root
  #     - MYSQL_PROXY_PASSWORD=password
  #     - DISCOVERY_SERVICE=false
  #   expose:
  #     - "6032"
  #   ports:
  #     # ProxySQL admin port for MySQL commands
  #     - "6032:6032"
  #     # ProxySQL main port
  #     - "6033:6033"

################################################
# openldap
  # openldap:
  #   container_name: openldap
  #   image: dataindataout/docker-openldap
  #   hostname: ldap
  #   ports:
  #     - "389:389"
  #     - "639:639"
  #   environment:
  #     - LDAP_ORGANISATION=proxysql
  #     - LDAP_DOMAIN=proxysql.com
  #     - LDAP_ADMIN_PASSWORD=password
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - /var/lib/ldap
  #     - /etc/ldap/slapd.d
  #     - /container/service/slapd/assets/certs/

################################################
# phpldapadmin (gui for openldap)
  # phpldapadmin:
  #   image: dataindataout/docker-phpldapadmin
  #   container_name: phpldapadmin
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: "openldap"
  #     PHPLDAPADMIN_HTTPS=false:
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - openldap

