version: '3'
services:

################################################
# servers to run a Cassandra cluster on

    C1:
        image: cassandra:latest
        hostname: C1
        networks:
          - myring
        volumes:
            - ./n1data:/var/lib/cassandra
            - ./configuration/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
        environment:
            - CASSANDRA_CLUSTER_NAME=dev_cluster
            - CASSANDRA_SEEDS=DC1N1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        command: tail -f /dev/null

    C2:
        image: cassandra:latest
        hostname: C2
        networks:
          - myring
        volumes:
            - ./n2data:/var/lib/cassandra
            - ./configuration/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
        environment:
            - CASSANDRA_CLUSTER_NAME=dev_cluster
            - CASSANDRA_SEEDS=C1
        depends_on:
              - C1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        command: tail -f /dev/null

    C3:
        image: cassandra:latest
        hostname: C3
        networks:
          - myring
        volumes:
            - ./n3data:/var/lib/cassandra
            - ./configuration/cassandra-env.sh:/etc/cassandra/cassandra-env.sh
        environment:
            - CASSANDRA_CLUSTER_NAME= dev_cluster
            - CASSANDRA_SEEDS=C1
        depends_on:
              - C1
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
        command: tail -f /dev/null

#####################################################
# pre-built ELK

    elasticsearch:
        image: elasticsearch:latest
        hostname: elasticsearch
        volumes:
          - ./configuration/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
          - myring

    logstash:
        image: logstash:latest
        hostname: logstash
        volumes:
          - ./configuration/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
          - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
          - "5000:5000"
        environment:
          LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
          - myring
        depends_on:
          - elasticsearch

    kibana:
        image: kibana:latest
        hostname: kibana
        volumes:
          - ./configuration/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        ports:
          - "5601:5601"
        networks:
          - myring
        depends_on:
          - elasticsearch

########################################################
# network

networks:
    myring:    
        driver: bridge



